use anyhow::Result;
use clap::{Args, Parser, Subcommand, ValueEnum};

use git_subrepo::{
    BranchArgs, CleanArgs, CloneArgs, CommitArgs, ConfigArgs, FetchArgs, InitArgs, JoinMethod,
    PatchesArgs, PatchesStyle, PullArgs, PushArgs, StatusArgs,
};

#[derive(Debug, Parser)]
#[command(name = "git-subrepo")]
#[command(about = "A user-friendly CLI for working with git-subrepo repositories")]
#[command(
    long_about = "A Rust implementation of git-subrepo.\n\nThis CLI focuses on a pleasant interactive experience (help text, clearer errors).\nCore semantics are validated using the upstream compatibility suite via the git-subrepo-compat harness.",
    after_help = "Examples:\n  git subrepo clone https://example.com/repo.git vendor/repo\n  git subrepo pull vendor/repo\n  git subrepo patches vendor/repo\n"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    Clone(CloneCmd),
    Init(InitCmd),
    Fetch(FetchCmd),
    Branch(BranchCmd),
    Pull(PullCmd),
    Push(PushCmd),
    Commit(CommitCmd),
    Status(StatusCmd),
    Clean(CleanCmd),
    Config(ConfigCmd),
    Patches(PatchesCmd),
    Version(VersionCmd),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum JoinMethodValue {
    Merge,
    Rebase,
}

impl From<JoinMethodValue> for JoinMethod {
    fn from(value: JoinMethodValue) -> Self {
        match value {
            JoinMethodValue::Merge => JoinMethod::Merge,
            JoinMethodValue::Rebase => JoinMethod::Rebase,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum PatchesStyleValue {
    Oneline,
    Decorate,
    Stat,
    NameStatus,
}

impl From<PatchesStyleValue> for PatchesStyle {
    fn from(value: PatchesStyleValue) -> Self {
        match value {
            PatchesStyleValue::Oneline => PatchesStyle::Oneline,
            PatchesStyleValue::Decorate => PatchesStyle::Decorate,
            PatchesStyleValue::Stat => PatchesStyle::Stat,
            PatchesStyleValue::NameStatus => PatchesStyle::NameStatus,
        }
    }
}

#[derive(Debug, Args)]
#[command(next_help_heading = "Commit message")]
struct MessageArgs {
    #[arg(
        short = 'm',
        long = "message",
        value_name = "MESSAGE",
        conflicts_with = "message_file",
        help = "Commit message to use (instead of the default autogenerated message)"
    )]
    message: Option<String>,

    #[arg(
        long = "file",
        value_name = "PATH",
        conflicts_with = "message",
        help = "Read the commit message from PATH"
    )]
    message_file: Option<String>,

    #[arg(
        long = "edit",
        short = 'e',
        help = "Open editor for the commit message"
    )]
    edit: bool,
}

#[derive(Debug, Args)]
#[command(about = "Clone a repository into a subdirectory as a subrepo")]
struct CloneCmd {
    #[arg(value_name = "REMOTE_URL", help = "Remote repository URL")]
    remote_url: String,

    #[arg(
        value_name = "SUBDIR",
        help = "Destination subdirectory (defaults to a name derived from REMOTE_URL)"
    )]
    subdir: Option<String>,

    #[arg(
        short = 'b',
        long = "branch",
        value_name = "BRANCH",
        help = "Upstream branch"
    )]
    branch: Option<String>,

    #[arg(
        short = 'f',
        long = "force",
        help = "Overwrite existing content if needed"
    )]
    force: bool,

    #[arg(
        long = "method",
        value_enum,
        default_value = "merge",
        help = "Join method used when integrating upstream changes"
    )]
    method: JoinMethodValue,

    #[command(flatten)]
    msg: MessageArgs,
}

#[derive(Debug, Args)]
#[command(about = "Initialize an existing subdirectory as a subrepo")]
struct InitCmd {
    #[arg(value_name = "SUBDIR", help = "Subdirectory to turn into a subrepo")]
    subdir: String,

    #[arg(
        short = 'r',
        long = "remote",
        value_name = "REMOTE_URL",
        help = "Upstream remote URL"
    )]
    remote: Option<String>,

    #[arg(
        short = 'b',
        long = "branch",
        value_name = "BRANCH",
        help = "Upstream branch"
    )]
    branch: Option<String>,

    #[arg(
        long = "method",
        value_enum,
        default_value = "merge",
        help = "Join method"
    )]
    method: JoinMethodValue,
}

#[derive(Debug, Args)]
#[command(about = "Fetch upstream content for a subrepo")]
struct FetchCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(
        short = 'r',
        long = "remote",
        value_name = "REMOTE_URL",
        help = "Override upstream remote"
    )]
    remote: Option<String>,

    #[arg(
        short = 'b',
        long = "branch",
        value_name = "BRANCH",
        help = "Override upstream branch"
    )]
    branch: Option<String>,

    #[arg(
        short = 'f',
        long = "force",
        help = "Fetch even if local state looks inconsistent"
    )]
    force: bool,
}

#[derive(Debug, Args)]
#[command(about = "Create or update the subrepo branch for SUBDIR")]
struct BranchCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(
        short = 'f',
        long = "force",
        help = "Overwrite existing branch/worktree if needed"
    )]
    force: bool,

    #[arg(short = 'F', long = "fetch", help = "Fetch upstream before branching")]
    fetch: bool,
}

#[derive(Debug, Args)]
#[command(about = "Pull upstream changes into the subrepo subdirectory")]
struct PullCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(
        short = 'f',
        long = "force",
        help = "Allow overwriting conflicting untracked files"
    )]
    force: bool,

    #[arg(
        short = 'r',
        long = "remote",
        value_name = "REMOTE_URL",
        help = "Override upstream remote"
    )]
    remote: Option<String>,

    #[arg(
        short = 'b',
        long = "branch",
        value_name = "BRANCH",
        help = "Override upstream branch"
    )]
    branch: Option<String>,

    #[arg(
        short = 'u',
        long = "update",
        help = "Update SUBDIR/.gitrepo with --remote/--branch overrides"
    )]
    update: bool,

    #[command(flatten)]
    msg: MessageArgs,
}

#[derive(Debug, Args)]
#[command(about = "Push local subrepo changes upstream")]
struct PushCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(short = 'f', long = "force", help = "Force push")]
    force: bool,

    #[arg(
        short = 's',
        long = "squash",
        help = "Squash local commits into a single upstream commit"
    )]
    squash: bool,

    #[arg(
        short = 'r',
        long = "remote",
        value_name = "REMOTE_URL",
        help = "Override upstream remote"
    )]
    remote: Option<String>,

    #[arg(
        short = 'b',
        long = "branch",
        value_name = "BRANCH",
        help = "Override upstream branch"
    )]
    branch: Option<String>,

    #[arg(
        short = 'u',
        long = "update",
        help = "Update SUBDIR/.gitrepo with --remote/--branch overrides"
    )]
    update: bool,

    #[command(flatten)]
    msg: MessageArgs,
}

#[derive(Debug, Args)]
#[command(about = "Commit the subrepo branch back into mainline history")]
struct CommitCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(
        value_name = "SUBREPO_REF",
        help = "Commit/ref in the subrepo branch to merge (defaults to the subrepo branch)"
    )]
    subrepo_ref: Option<String>,

    #[arg(short = 'f', long = "force", help = "Skip certain safety checks")]
    force: bool,

    #[arg(short = 'F', long = "fetch", help = "Fetch upstream before committing")]
    fetch: bool,

    #[command(flatten)]
    msg: MessageArgs,
}

#[derive(Debug, Args)]
#[command(about = "Show status for one or more subrepos")]
struct StatusCmd {
    #[arg(
        value_name = "SUBDIR",
        conflicts_with_all = ["all", "all_all"],
        help = "Show status for a single subrepo"
    )]
    subdir: Option<String>,

    #[arg(long = "all", help = "Show status for all top-level subrepos")]
    all: bool,

    #[arg(
        long = "ALL",
        help = "Show status for all subrepos, including nested ones"
    )]
    all_all: bool,

    #[arg(
        short = 'F',
        long = "fetch",
        help = "Fetch upstream for each selected subrepo"
    )]
    fetch: bool,

    #[arg(
        short = 'q',
        long = "quiet",
        help = "Print only subdir names (one per line)"
    )]
    quiet: bool,
}

#[derive(Debug, Args)]
#[command(about = "Remove local artifacts created by subrepo commands")]
struct CleanCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(short = 'f', long = "force", help = "Also delete refs and backup refs")]
    force: bool,
}

#[derive(Debug, Args)]
#[command(about = "Read or update values in SUBDIR/.gitrepo")]
struct ConfigCmd {
    #[arg(value_name = "SUBDIR", help = "Subrepo subdirectory")]
    subdir: String,

    #[arg(
        value_name = "OPTION",
        help = "Option name (remote|branch|commit|parent|method|cmdver|version)"
    )]
    option: String,

    #[arg(value_name = "VALUE", help = "New value (omit to show current value)")]
    value: Option<String>,

    #[arg(
        short = 'f',
        long = "force",
        help = "Allow changing autogenerated options"
    )]
    force: bool,
}

#[derive(Debug, Args)]
#[command(
    about = "Show local mainline commits affecting a subrepo since the last sync",
    after_help = "Examples:\n  git subrepo patches vendor/repo\n  git subrepo patches vendor/repo --since HEAD~20\n  git subrepo patches vendor/repo --update-ref\n  git subrepo patches --all\n"
)]
struct PatchesCmd {
    #[arg(
        value_name = "SUBDIR",
        conflicts_with_all = ["all", "all_all"],
        help = "Subrepo subdirectory"
    )]
    subdir: Option<String>,

    #[arg(long = "all", help = "List patches for all top-level subrepos")]
    all: bool,

    #[arg(
        long = "ALL",
        help = "List patches for all subrepos, including nested ones"
    )]
    all_all: bool,

    #[arg(
        long = "since",
        value_name = "REV",
        conflicts_with_all = ["from_ref", "since_sync"],
        help = "Start listing patches after REV"
    )]
    since: Option<String>,

    #[arg(
        long = "from-ref",
        value_name = "REF",
        conflicts_with_all = ["since", "since_sync"],
        help = "Start listing patches after REF (any ref name accepted)"
    )]
    from_ref: Option<String>,

    #[arg(
        long = "since-sync",
        conflicts_with_all = ["since", "from_ref"],
        help = "Force commit-message anchor detection (ignore refs/subrepo/<subref>/sync)"
    )]
    since_sync: bool,

    #[arg(
        long = "update-ref",
        help = "Update the baseline ref to the current HEAD"
    )]
    update_ref: bool,

    #[arg(
        long = "ref-name",
        value_name = "REF",
        help = "Ref name to update when using --update-ref (defaults to refs/subrepo/<subref>/baseline)"
    )]
    ref_name: Option<String>,

    #[arg(
        long = "style",
        value_enum,
        default_value = "oneline",
        help = "Output style"
    )]
    style: PatchesStyleValue,

    #[arg(long = "reverse", help = "Reverse output order")]
    reverse: bool,
}

#[derive(Debug, Args)]
#[command(about = "Print version information")]
struct VersionCmd {
    #[arg(short = 'q', long = "quiet", help = "Print only the version number")]
    quiet: bool,
}

fn main() {
    if let Err(err) = try_main() {
        eprintln!("error: {err}");
        std::process::exit(1);
    }
}

fn try_main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Clone(cmd) => {
            let out = git_subrepo::clone(CloneArgs {
                remote: cmd.remote_url,
                subdir: cmd.subdir,
                branch: cmd.branch,
                force: cmd.force,
                method: cmd.method.into(),
                message: cmd.msg.message,
                message_file: cmd.msg.message_file,
                edit: cmd.msg.edit,
            })?;
            print_out(out);
        }
        Command::Init(cmd) => {
            let out = git_subrepo::init(InitArgs {
                subdir: cmd.subdir,
                remote: cmd.remote,
                branch: cmd.branch,
                method: cmd.method.into(),
            })?;
            print_out(out);
        }
        Command::Fetch(cmd) => {
            let out = git_subrepo::fetch(FetchArgs {
                subdir: cmd.subdir,
                remote: cmd.remote,
                branch: cmd.branch,
                force: cmd.force,
            })?;
            print_out(out);
        }
        Command::Branch(cmd) => {
            let out = git_subrepo::branch(BranchArgs {
                subdir: cmd.subdir,
                force: cmd.force,
                fetch: cmd.fetch,
            })?;
            print_out(out);
        }
        Command::Pull(cmd) => {
            let out = git_subrepo::pull(PullArgs {
                subdir: cmd.subdir,
                force: cmd.force,
                remote: cmd.remote,
                branch: cmd.branch,
                update: cmd.update,
                message: cmd.msg.message,
                message_file: cmd.msg.message_file,
                edit: cmd.msg.edit,
            })?;
            print_out(out);
        }
        Command::Push(cmd) => {
            let out = git_subrepo::push(PushArgs {
                subdir: cmd.subdir,
                force: cmd.force,
                squash: cmd.squash,
                remote: cmd.remote,
                branch: cmd.branch,
                update: cmd.update,
                message: cmd.msg.message,
                message_file: cmd.msg.message_file,
            })?;
            print_out(out);
        }
        Command::Commit(cmd) => {
            let out = git_subrepo::commit(CommitArgs {
                subdir: cmd.subdir,
                commit_ref: cmd.subrepo_ref,
                force: cmd.force,
                fetch: cmd.fetch,
                message: cmd.msg.message,
                message_file: cmd.msg.message_file,
                edit: cmd.msg.edit,
            })?;
            print_out(out);
        }
        Command::Status(cmd) => {
            if cmd.quiet {
                let include_nested = cmd.all_all;
                for s in git_subrepo::subrepos(include_nested)? {
                    println!("{s}");
                }
            } else {
                let out = git_subrepo::status(StatusArgs {
                    subdir: cmd.subdir,
                    all: cmd.all,
                    all_all: cmd.all_all,
                    fetch: cmd.fetch,
                })?;
                print_out(out);
            }
        }
        Command::Clean(cmd) => {
            let removed = git_subrepo::clean(CleanArgs {
                subdir: cmd.subdir,
                force: cmd.force,
            })?;
            if !removed.is_empty() {
                println!("{}", removed.join("\n"));
            }
        }
        Command::Config(cmd) => {
            let out = git_subrepo::config(ConfigArgs {
                subdir: cmd.subdir,
                option: cmd.option,
                value: cmd.value,
                force: cmd.force,
            })?;
            print_out(out);
        }
        Command::Patches(cmd) => {
            let out = git_subrepo::patches(PatchesArgs {
                subdir: cmd.subdir,
                all: cmd.all,
                all_all: cmd.all_all,
                since: cmd.since,
                from_ref: cmd.from_ref,
                since_sync: cmd.since_sync,
                update_ref: cmd.update_ref,
                ref_name: cmd.ref_name,
                style: cmd.style.into(),
                reverse: cmd.reverse,
            })?;
            print_out(out);
        }
        Command::Version(cmd) => {
            if !cmd.quiet {
                println!("{}", git_subrepo::VERSION);
            }
        }
    }

    Ok(())
}

fn print_out(out: String) {
    if !out.is_empty() {
        println!("{out}");
    }
}
